version: '3.7'
services:
  web:
    build: 
      context: .
    command: node app.js
    volumes: 
      - /app/node_modules
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    